Bump go
docker/packaging pull request #128
Opened 2023-05-25 23:56 UTC by crazy-max

2023-05-26 00:10 UTC, neersighted reviewed
Is there a reason we only bumped `credential-helpers` to 1.20.3?

2023-05-26 09:24 UTC, crazy-max commented
> Is there a reason we only bumped `credential-helpers` to 1.20.3?

Yeah this is still 1.20.3 on def branch: https://github.com/docker/docker-credential-helpers/blob/da93839996460f358368e183cbd8da06feae3fec/Dockerfile#L3

2023-05-27 15:53 UTC, neersighted approved these changes

2023-05-27 16:47 UTC, thaJeztah commented
@crazy-max I added @neersighted as collaborator on this repo ("maintainer" access).

We should probably look at creating a "packagers" or "release" team that we can use to give access to the (etoomany) repositories we have related to that now. (perhaps we need separate teams for the internal (private) and external repos though)

2023-05-27 16:48 UTC, thaJeztah approved these changes
LGTM as well 👍

2023-05-27 16:49 UTC, thaJeztah commented
> Yeah this is still 1.20.3 on def branch: https://github.com/docker/docker-credential-helpers/blob/da93839996460f358368e183cbd8da06feae3fec/Dockerfile#L3


I think we should be good updating it to 1.20.4 in this repo though (other repo should be updated as well; let me open a PR for that)

2023-05-27 16:59 UTC, thaJeztah commented
- opened https://github.com/docker/docker-credential-helpers/pull/281

2023-05-27 17:55 UTC, neersighted commented
I'm not sure we need separate teams, as to join a team you have to be part of the org (I think); thus any external (non-Docker Inc.) collaborators need to be non-team members. Maybe I'm wrong on that, through.

2023-05-27 17:55 UTC, neersighted requested changes
Blocking on cred-helper update to 1.20.4

2023-05-27 21:03 UTC, thaJeztah approved these changes
LGTM

2023-05-27 21:07 UTC, neersighted approved these changes

2023-05-28 13:44 UTC, merged